spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shellweprototype?useSSL=false
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
  sql:
    init:
      data-locations: classpath*:db/mysql/data.sql
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH_SECRET_KEY}
            scope:
              - profile
              - email
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:                   # 모든 response 에 대해 지정된 인코딩 적용(한글 깨짐 방지)
  port: 8081
  servlet:
    encoding:
      force-response: true
jwt:                      # JWT 관련 정보
  key: ${JWT_SECRET_KEY}  # 시스템 환경 변수에서 로드
  access-token-expiration-minutes: 2000
  refresh-token-expiration-minutes: 600
client_server:
  url: http://localhost:3000